/*
Navicat MySQL Data Transfer

Source Server         : PHPMyAdmin
Source Server Version : 50611
Source Host           : 127.0.0.1:3306
Source Database       : db_kanaka

Target Server Type    : MYSQL
Target Server Version : 50611
File Encoding         : 65001

Date: 2019-05-07 23:35:29
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for logs
-- ----------------------------
DROP TABLE IF EXISTS `logs`;
CREATE TABLE `logs` (
  `id_logs` int(11) NOT NULL AUTO_INCREMENT,
  `id_user` int(11) unsigned NOT NULL,
  `data_new` text,
  `data_old` text,
  `data_change` text,
  `message` text NOT NULL,
  `created_on` datetime NOT NULL,
  `activity` enum('C','U','D') NOT NULL,
  `type` int(11) NOT NULL,
  PRIMARY KEY (`id_logs`),
  KEY `users_id` (`id_user`)
) ENGINE=InnoDB AUTO_INCREMENT=187 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of logs
-- ----------------------------
INSERT INTO `logs` VALUES ('1', '1', '{\"Kode Menu\":1}', '{\"Kode Menu\":3}', '{\"Kode Menu\":1}', 'menu Reports berhasil diubah oleh Administrator', '2017-10-11 15:45:03', 'U', '1');
INSERT INTO `logs` VALUES ('2', '1', '{\"Kode Menu\":3}', '{\"Kode Menu\":1}', '{\"Kode Menu\":3}', 'menu Reports berhasil diubah oleh Administrator', '2017-10-11 15:45:49', 'U', '1');
INSERT INTO `logs` VALUES ('3', '1', '{\"Kode Menu\":\"6\",\"Nama Menu\":\"TesT\",\"Link Menu\":\"teSt_li\",\"Lang\":\"Test_Lang\",\"Parent Menu\":\"-\",\"Status\":\"1\"}', null, null, 'Add menu TesT succesfully by Administrator', '2017-10-11 16:19:51', 'C', '1');
INSERT INTO `logs` VALUES ('4', '1', '{\"Kode Menu\":\"6\",\"Nama Menu\":\"TesT1\",\"Link Menu\":\"teSt_lin\",\"Lang\":\"Test_Langu\",\"Parent Menu\":\"Reports\",\"Status\":\"0\"}', '{\"Kode Menu\":6,\"Nama Menu\":\"TesT\",\"Link Menu\":\"teSt_li\",\"Lang\":\"Test_Lang\",\"Parent Menu\":\"-\",\"Status\":\"1\"}', '{\"Nama Menu\":\"TesT1\",\"Link Menu\":\"teSt_lin\",\"Lang\":\"Test_Langu\",\"Parent Menu\":\"Reports\",\"Status\":\"0\"}', 'Update menu TesT1 succesfully by Administrator', '2017-10-11 16:20:41', 'U', '1');
INSERT INTO `logs` VALUES ('5', '1', null, '{\"Kode Menu\":6,\"Nama Menu\":\"TesT1\",\"Link Menu\":\"teSt_lin\",\"Lang\":\"Test_Langu\",\"Parent Menu\":\"Reports\",\"Status\":\"0\"}', null, 'Delete menu TesT1 succesfully by Administrator', '2017-10-11 16:21:11', 'D', '1');
INSERT INTO `logs` VALUES ('6', '1', '{\"Kode Menu\":\"6\",\"Nama Menu\":\"Test\",\"Link Menu\":\"test\",\"Lang\":\"tses\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', null, null, 'Add menu Test succesfully by Administrator', '2017-10-11 17:02:05', 'C', '1');
INSERT INTO `logs` VALUES ('7', '1', '{\"Kode Menu\":\"6\",\"Nama Menu\":\"Test\",\"Link Menu\":\"test\",\"Lang\":\"tses\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', '{\"Kode Menu\":6,\"Nama Menu\":\"Test\",\"Link Menu\":\"test\",\"Lang\":\"tses\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', '[]', 'Update menu Test succesfully by Administrator', '2017-10-11 17:13:23', 'U', '1');
INSERT INTO `logs` VALUES ('8', '1', '{\"Kode Menu\":\"8\",\"Nama Menu\":\"Test\",\"Link Menu\":\"Test1\",\"Lang\":\"Test\",\"Parent Menu\":\"Reports\",\"Status\":\"1\"}', '{\"Kode Menu\":8,\"Nama Menu\":\"Test\",\"Link Menu\":\"Test\",\"Lang\":\"Test\",\"Parent Menu\":\"Reports\",\"Status\":\"1\"}', '{\"Link Menu\":\"Test1\"}', 'Update menu Test succesfully by Administrator', '2017-10-11 17:21:19', 'U', '1');
INSERT INTO `logs` VALUES ('9', '1', '{\"Kode Menu\":\"10\",\"Nama Menu\":\"Resr\",\"Link Menu\":\"Test\",\"Lang\":\"setrse\",\"Parent Menu\":\"Transaction\",\"Status\":\"1\"}', null, null, 'Add menu Resr succesfully by Administrator', '2017-10-11 17:25:39', 'C', '1');
INSERT INTO `logs` VALUES ('10', '1', '{\"Kode Menu\":\"6\",\"Nama Menu\":\"History\",\"Link Menu\":\"history\",\"Lang\":\"history\",\"Parent Menu\":\"-\",\"Status\":\"1\"}', '{\"Kode Menu\":6,\"Nama Menu\":\"Test\",\"Link Menu\":\"test\",\"Lang\":\"tses\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', '{\"Nama Menu\":\"History\",\"Link Menu\":\"history\",\"Lang\":\"history\",\"Parent Menu\":\"-\"}', 'Update menu History succesfully by Administrator', '2017-10-11 17:35:30', 'U', '1');
INSERT INTO `logs` VALUES ('11', '1', '{\"Kode Menu\":\"11\",\"Nama Menu\":\"Las\",\"Link Menu\":\"te\",\"Lang\":\"Te\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', null, null, 'Add menu Las succesfully by Administrator', '2017-10-11 18:33:15', 'C', '1');
INSERT INTO `logs` VALUES ('12', '1', '{\"Kode Menu\":\"11\",\"Nama Menu\":\"Las\",\"Link Menu\":\"tea\",\"Lang\":\"Te\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', '{\"Kode Menu\":11,\"Nama Menu\":\"Las\",\"Link Menu\":\"te\",\"Lang\":\"Te\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', '{\"Link Menu\":\"tea\"}', 'Update menu Las succesfully by Administrator', '2017-10-11 18:33:45', 'U', '1');
INSERT INTO `logs` VALUES ('13', '1', '{\"Kode Menu\":10}', '{\"Kode Menu\":11}', '{\"Kode Menu\":10}', 'Update menu Las succesfully by Administrator', '2017-10-11 18:34:30', 'U', '1');
INSERT INTO `logs` VALUES ('14', '1', null, '{\"Kode Menu\":10,\"Nama Menu\":\"Las\",\"Link Menu\":\"tea\",\"Lang\":\"Te\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', null, 'Delete menu Las succesfully by Administrator', '2017-10-11 18:34:52', 'D', '1');
INSERT INTO `logs` VALUES ('15', '1', '{\"Kode Menu\":\"10\",\"Nama Menu\":\"Resr\",\"Link Menu\":\"Test\",\"Lang\":\"setrse\",\"Parent Menu\":\"Transaction\",\"Status\":\"1\"}', '{\"Kode Menu\":10,\"Nama Menu\":\"Resr\",\"Link Menu\":\"Test\",\"Lang\":\"setrse\",\"Parent Menu\":\"Transaction\",\"Status\":\"1\"}', '[]', 'Update menu Resr succesfully by Administrator', '2017-10-11 18:35:25', 'U', '1');
INSERT INTO `logs` VALUES ('16', '1', null, '{\"Kode Menu\":10,\"Nama Menu\":\"Resr\",\"Link Menu\":\"Test\",\"Lang\":\"setrse\",\"Parent Menu\":\"Transaction\",\"Status\":\"1\"}', null, 'Delete menu Resr succesfully by Administrator', '2017-10-12 09:12:00', 'D', '1');
INSERT INTO `logs` VALUES ('17', '1', '{\"Kode Menu\":\"9\",\"Nama Menu\":\"Test2\",\"Link Menu\":\"Test2\",\"Lang\":\"Test2\",\"Parent Menu\":\"Reports\",\"Status\":\"0\"}', '{\"Kode Menu\":9,\"Nama Menu\":\"Test\",\"Link Menu\":\"Test\",\"Lang\":\"Test\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', '{\"Nama Menu\":\"Test2\",\"Link Menu\":\"Test2\",\"Lang\":\"Test2\",\"Parent Menu\":\"Reports\",\"Status\":\"0\"}', 'Update menu Test2 succesfully by Administrator', '2017-10-12 09:12:30', 'U', '1');
INSERT INTO `logs` VALUES ('18', '1', '{\"Kode Menu\":\"10\",\"Nama Menu\":\"Na\",\"Link Menu\":\"nad\",\"Lang\":\"naaa\",\"Parent Menu\":\"Master\",\"Status\":\"0\"}', null, null, 'Add menu Na succesfully by Administrator', '2017-10-12 09:13:09', 'C', '1');
INSERT INTO `logs` VALUES ('19', '1', '{\"Kode Menu\":\"9\",\"Nama Menu\":\"Test2\",\"Link Menu\":\"Test2\",\"Lang\":\"Test2\",\"Parent Menu\":\"Reports\",\"Status\":\"1\"}', '{\"Kode Menu\":9,\"Nama Menu\":\"Test2\",\"Link Menu\":\"Test2\",\"Lang\":\"Test2\",\"Parent Menu\":\"Reports\",\"Status\":\"0\"}', '{\"Status\":\"1\"}', 'Update menu Test2 succesfully by Administrator', '2017-10-12 09:13:35', 'U', '1');
INSERT INTO `logs` VALUES ('20', '1', '{\"Kode Menu\":\"11\",\"Nama Menu\":\"as\",\"Link Menu\":\"das\",\"Lang\":\"asd\",\"Parent Menu\":\"History\",\"Status\":\"Not Active\"}', null, null, 'Add menu as succesfully by Administrator', '2017-10-12 09:15:20', 'C', '1');
INSERT INTO `logs` VALUES ('21', '1', '{\"Kode Menu\":\"11\",\"Nama Menu\":\"as\",\"Link Menu\":\"das\",\"Lang\":\"asd\",\"Parent Menu\":\"Master\",\"Status\":\"1\"}', '{\"Kode Menu\":11,\"Nama Menu\":\"as\",\"Link Menu\":\"das\",\"Lang\":\"asd\",\"Parent Menu\":\"History\",\"Status\":\"Not Active\"}', '{\"Parent Menu\":\"Master\",\"Status\":\"1\"}', 'Update menu as succesfully by Administrator', '2017-10-12 09:15:39', 'U', '1');
INSERT INTO `logs` VALUES ('22', '1', '{\"Kode Menu\":12}', '{\"Kode Menu\":11}', '{\"Kode Menu\":12}', 'Update menu as succesfully by Administrator', '2017-10-12 09:15:53', 'U', '1');
INSERT INTO `logs` VALUES ('23', '1', null, '{\"Kode Menu\":12,\"Nama Menu\":\"as\",\"Link Menu\":\"das\",\"Lang\":\"asd\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', null, 'Delete menu as succesfully by Administrator', '2017-10-12 09:16:00', 'D', '1');
INSERT INTO `logs` VALUES ('24', '1', '{\"Kode Menu\":\"10\",\"Nama Menu\":\"Na\",\"Link Menu\":\"nad\",\"Lang\":\"naaa\",\"Parent Menu\":\"History\",\"Status\":\"Active\"}', '{\"Kode Menu\":10,\"Nama Menu\":\"Na\",\"Link Menu\":\"nad\",\"Lang\":\"naaa\",\"Parent Menu\":\"Master\",\"Status\":\"Not Active\"}', '{\"Parent Menu\":\"History\",\"Status\":\"Active\"}', 'Update menu Na succesfully by Administrator', '2017-10-12 09:17:10', 'U', '1');
INSERT INTO `logs` VALUES ('25', '1', null, '{\"Kode Menu\":10,\"Nama Menu\":\"Na\",\"Link Menu\":\"nad\",\"Lang\":\"naaa\",\"Parent Menu\":\"History\",\"Status\":\"Active\"}', null, 'Delete menu Na succesfully by Administrator', '2017-10-12 09:17:33', 'D', '1');
INSERT INTO `logs` VALUES ('26', '1', '{\"Kode Menu\":\"6\",\"Nama Menu\":\"History\",\"Link Menu\":\"history\",\"Lang\":\"history\",\"Parent Menu\":\"-\",\"Status\":\"Not Active\"}', '{\"Kode Menu\":6,\"Nama Menu\":\"History\",\"Link Menu\":\"history\",\"Lang\":\"history\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Status\":\"Not Active\"}', 'Update menu History succesfully by Administrator', '2017-10-12 09:17:42', 'U', '1');
INSERT INTO `logs` VALUES ('27', '1', null, '{\"Kode Menu\":9,\"Nama Menu\":\"Test2\",\"Link Menu\":\"Test2\",\"Lang\":\"Test2\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', null, 'Delete menu Test2 succesfully by Administrator', '2017-10-12 09:18:04', 'D', '1');
INSERT INTO `logs` VALUES ('28', '1', null, '{\"Kode Menu\":7,\"Nama Menu\":\"Test\",\"Link Menu\":\"Test\",\"Lang\":\"TEst\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', null, 'Delete menu Test succesfully by Administrator', '2017-10-12 09:18:33', 'D', '1');
INSERT INTO `logs` VALUES ('29', '1', null, '{\"Kode Menu\":8,\"Nama Menu\":\"Test\",\"Link Menu\":\"Test1\",\"Lang\":\"Test\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', null, 'Delete menu Test succesfully by Administrator', '2017-10-12 09:18:38', 'D', '1');
INSERT INTO `logs` VALUES ('30', '1', '{\"Full Name\":\"Sandhy\",\"Email\":\"Sandhy@gmail.com\",\"Role\":\"General User\",\"Company\":\"Test\",\"Phone\":\"\"}', null, null, 'Administrator berhasil menambahkan pengguna  Sandhy@gmail.com', '2017-10-12 10:28:11', 'C', '2');
INSERT INTO `logs` VALUES ('31', '1', '{\"Full Name\":\"a\",\"Email\":\"abbay89@gmail.com\",\"Role\":\"General User\",\"Company\":\"asda\",\"Phone\":\"\"}', null, null, 'Administrator berhasil menambahkan pengguna  abbay89@gmail.com', '2017-10-12 10:45:38', 'C', '2');
INSERT INTO `logs` VALUES ('32', '1', '{\"Full Name\":\"Fajar\",\"Email\":\"Fajar@gmail.com\",\"Role\":\"Administrator\",\"Company\":\"Nadyne\",\"Phone\":\"\"}', null, null, 'Administrator berhasil menambahkan pengguna  Fajar@gmail.com', '2017-10-12 10:48:08', 'C', '2');
INSERT INTO `logs` VALUES ('33', '1', '{\"Full Name\":\"Sandhy\",\"Email\":\"Sandhy@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"08123456789\",\"City\":\"Depok\",\"VAT\":null,\"Address\":\"Jalan margonda\",\"Role \":\"General User\"}', '{\"Full Name\":\"Sandhy\",\"Email\":\"Sandhy@gmail.com\",\"Company\":\"Test\",\"Phone\":\"0812345\",\"City\":null,\"VAT\":null,\"Address\":null,\"Role \":\"General User\"}', '{\"Company\":\"Nadyne\",\"Phone\":\"08123456789\",\"City\":\"Depok\",\"Address\":\"Jalan margonda\"}', 'pengguna Sandhy@gmail.com berhasil diubah oleh Administrator', '2017-10-12 11:01:45', 'U', '2');
INSERT INTO `logs` VALUES ('34', '1', '{\"Full Name\":\"Sandhy\",\"Email\":\"Sandhy@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"08123456789\",\"City\":\"Depok\",\"Address\":\"Jalan Margonda\",\"Role \":\"Administrator\"}', '{\"Full Name\":\"Sandhy\",\"Email\":\"Sandhy@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"08123456789\",\"City\":\"Depok\",\"Address\":\"Jalan margonda\",\"Role \":\"General User\"}', '{\"Address\":\"Jalan Margonda\",\"Role \":\"Administrator\"}', 'pengguna Sandhy@gmail.com berhasil diubah oleh Administrator', '2017-10-12 11:03:38', 'U', '2');
INSERT INTO `logs` VALUES ('35', '1', '{\"Full Name\":\"Akbar\",\"Email\":\"abbay89@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"08123456789\",\"City\":\"Jakarta\",\"Address\":\"Jalan Benda\",\"Role \":\"Administrator\"}', '{\"Full Name\":\"a\",\"Email\":\"abbay89@gmail.com\",\"Company\":\"asda\",\"Phone\":\"a\",\"City\":null,\"Address\":null,\"Role \":\"General User\"}', '{\"Full Name\":\"Akbar\",\"Company\":\"Nadyne\",\"Phone\":\"08123456789\",\"City\":\"Jakarta\",\"Address\":\"Jalan Benda\",\"Role \":\"Administrator\"}', 'pengguna abbay89@gmail.com berhasil diubah oleh Administrator', '2017-10-12 11:05:37', 'U', '2');
INSERT INTO `logs` VALUES ('36', '1', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"\",\"Address\":\"\",\"Role \":\"Administrator\"}', '{\"Full Name\":\"Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":null,\"Address\":null,\"Role \":\"Administrator\"}', '{\"Full Name\":\"Muhammad Fajar\"}', 'pengguna Fajar@gmail.com berhasil diubah oleh Administrator', '2017-10-12 11:36:19', 'U', '2');
INSERT INTO `logs` VALUES ('37', '1', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"Bogo\",\"Address\":\"Cileungsi\",\"Role \":\"Administrator\"}', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"\",\"Address\":\"\",\"Role \":\"Administrator\"}', '{\"City\":\"Bogo\",\"Address\":\"Cileungsi\"}', 'pengguna Fajar@gmail.com berhasil diubah oleh Administrator', '2017-10-12 11:36:46', 'U', '2');
INSERT INTO `logs` VALUES ('38', '1', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"Bogor\",\"Address\":\"Cileungsi\",\"Role \":\"Administrator\"}', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"Bogo\",\"Address\":\"Cileungsi\",\"Role \":\"Administrator\"}', '{\"City\":\"Bogor\"}', 'pengguna Fajar@gmail.com berhasil diubah oleh Administrator', '2017-10-12 11:37:08', 'U', '2');
INSERT INTO `logs` VALUES ('39', '1', '{\"Active\":\"Not Active\"}', '{\"Active\":\"Active\"}', '{\"Active\":\"Not Active\"}', 'pengguna Administrator berhasil diubah oleh Administrator', '2017-10-12 11:38:03', 'U', '2');
INSERT INTO `logs` VALUES ('40', '1', '{\"Active\":\"Not Active\"}', '{\"Active\":\"Active\"}', '{\"Active\":\"Not Active\"}', 'pengguna Administrator berhasil diubah oleh Administrator', '2017-10-12 11:45:24', 'U', '2');
INSERT INTO `logs` VALUES ('41', '1', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"Bogor\",\"Address\":\"Cileungsi\",\"Role \":\"Administrator\"}', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"Bogor\",\"Address\":\"Cileungsi\",\"Role \":\"Administrator\"}', '[]', 'pengguna Fajar@gmail.com berhasil diubah oleh Administrator', '2017-10-12 11:45:39', 'U', '2');
INSERT INTO `logs` VALUES ('42', '1', '{\"Full Name\":\"Rizki\",\"Email\":\"rizki@gmail.com\",\"Role\":\"General User\",\"Company\":\"Nadyne\",\"Phone\":\"08123456\"}', null, null, 'Add user Rizki succesfully by Administrator', '2017-10-12 13:14:43', 'C', '2');
INSERT INTO `logs` VALUES ('43', '1', '{\"Full Name\":\"Rizki\",\"Email\":\"rizki@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"08123456\",\"City\":\"Jakarta\",\"Address\":\"Halim\",\"Role \":\"General User\"}', '{\"Full Name\":\"Rizki\",\"Email\":\"rizki@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"08123456\",\"City\":null,\"Address\":null,\"Role \":\"General User\"}', '{\"City\":\"Jakarta\",\"Address\":\"Halim\"}', 'Update user Rizki succesfully by Administrator', '2017-10-12 13:15:46', 'U', '2');
INSERT INTO `logs` VALUES ('44', '1', '{\"Full Name\":\"Rizki\",\"Email\":\"rizki@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"081234567\",\"City\":\"Jakarta\",\"Address\":\"Halim\",\"Role \":\"Administrator\"}', '{\"Full Name\":\"Rizki\",\"Email\":\"rizki@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"08123456\",\"City\":\"Jakarta\",\"Address\":\"Halim\",\"Role \":\"General User\"}', '{\"Phone\":\"081234567\",\"Role \":\"Administrator\"}', 'Update user Rizki succesfully by Administrator', '2017-10-12 13:16:16', 'U', '2');
INSERT INTO `logs` VALUES ('45', '1', '{\"Full Name\":\"Rizki\",\"Email\":\"rizki@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"081234567\",\"City\":\"Jakarta\",\"Address\":\"Halim\",\"Role \":\"General User\"}', '{\"Full Name\":\"Rizki\",\"Email\":\"rizki@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"081234567\",\"City\":\"Jakarta\",\"Address\":\"Halim\",\"Role \":\"Administrator\"}', '{\"Role \":\"General User\"}', 'Update user Rizki succesfully by Administrator', '2017-10-12 13:17:32', 'U', '2');
INSERT INTO `logs` VALUES ('46', '1', '{\"Active\":\"Not Active\"}', '{\"Active\":\"Active\"}', '{\"Active\":\"Not Active\"}', 'Delete user Administrator succesfully by Administrator', '2017-10-12 13:18:35', 'U', '2');
INSERT INTO `logs` VALUES ('47', '1', '{\"Full Name\":\"Test\",\"Email\":\"ytayst@gmail.com\",\"Role\":\"Administrator\",\"Company\":\"Nadyne\",\"Phone\":\"089\"}', null, null, 'Add user Test succesfully by Administrator', '2017-10-12 13:21:32', 'C', '2');
INSERT INTO `logs` VALUES ('48', '1', '{\"Active\":\"Not Active\"}', '{\"Active\":\"Active\"}', '{\"Active\":\"Not Active\"}', 'Delete user Test succesfully by Administrator', '2017-10-12 13:21:38', 'U', '2');
INSERT INTO `logs` VALUES ('49', '1', '{\"Active\":\"Not Active\"}', '{\"Active\":\"Active\"}', '{\"Active\":\"Not Active\"}', 'Delete user Rizki succesfully by Administrator', '2017-10-12 13:23:16', 'D', '2');
INSERT INTO `logs` VALUES ('50', '1', null, '{\"Status\":\"Active\"}', null, 'Delete user Rizki succesfully by Administrator', '2017-10-12 13:27:59', 'D', '2');
INSERT INTO `logs` VALUES ('51', '1', '{\"User\":\"Muhammad Fajar\",\"Menu\":\"Master\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"NO\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:07:11', 'C', '3');
INSERT INTO `logs` VALUES ('52', '1', '{\"Menu\":\"Master\",\"Availabled\":\"No\",\"Created\":\"No\",\"Viewed\":\"No\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"No\",\"Verified\":\"No\",\"Fullaccess\":\"No\",\"Print Limited\":\"Yes\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Master\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Availabled\":\"No\",\"Created\":\"No\",\"Viewed\":\"No\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"No\",\"Verified\":\"No\",\"Fullaccess\":\"No\",\"Print Limited\":\"Yes\",\"Print Unlimited\":\"No\"}', 'Update user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:14:47', 'U', '3');
INSERT INTO `logs` VALUES ('53', '1', '{\"Menu\":\"Master\",\"Availabled\":\"No\",\"Created\":\"No\",\"Viewed\":\"No\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"No\",\"Verified\":\"No\",\"Fullaccess\":\"No\",\"Print Limited\":\"Yes\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Master\",\"Availabled\":\"No\",\"Created\":\"No\",\"Viewed\":\"No\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"No\",\"Verified\":\"No\",\"Fullaccess\":\"No\",\"Print Limited\":\"Yes\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '[]', 'Update user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:22:49', 'U', '3');
INSERT INTO `logs` VALUES ('54', '1', '{\"User\":\"Muhammad Fajar\",\"Menu\":\"Transaction\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:23:05', 'C', '3');
INSERT INTO `logs` VALUES ('55', '1', '{\"User\":\"Muhammad Fajar\",\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:29:42', 'C', '3');
INSERT INTO `logs` VALUES ('56', '1', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Print Unlimited\":\"No\"}', 'Update user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:30:25', 'U', '3');
INSERT INTO `logs` VALUES ('57', '1', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"No\"}', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Status Usermenu\":\"No\"}', 'Update user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:30:36', 'U', '3');
INSERT INTO `logs` VALUES ('58', '1', '{\"User\":\"Muhammad Fajar\",\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Not Active\"}', null, null, 'Add user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:32:21', 'C', '3');
INSERT INTO `logs` VALUES ('59', '1', '{\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"Yes\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Not Active\"}', '{\"Print Limited\":\"Yes\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', 'Update user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:33:44', 'U', '3');
INSERT INTO `logs` VALUES ('60', '1', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"Yes\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Users\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\"}', 'Update user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:35:18', 'U', '3');
INSERT INTO `logs` VALUES ('61', '1', '{\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Not Active\"}', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Not Active\"}', '{\"Menu\":\"Reports\"}', 'Update user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:36:23', 'U', '3');
INSERT INTO `logs` VALUES ('62', '1', '{\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Not Active\"}', '{\"Status Usermenu\":\"Active\"}', 'Update user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:36:47', 'U', '3');
INSERT INTO `logs` VALUES ('63', '1', '{\"Status Usermenu\":\"Not Active\"}', '{\"Status Usermenu\":\"Active\"}', '{\"Status Usermenu\":\"Not Active\"}', 'Delete user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 14:37:13', 'U', '3');
INSERT INTO `logs` VALUES ('64', '5', '{\"Full Name\":\"Octavian Panggestu\",\"Email\":\"octavian@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Bogor\",\"Address\":\"Cilebut\",\"Role \":\"General User\"}', '{\"Full Name\":\"Member\",\"Email\":\"\",\"Company\":null,\"Phone\":\"\",\"City\":null,\"Address\":null,\"Role \":\"General User\"}', '{\"Full Name\":\"Octavian Panggestu\",\"Email\":\"octavian@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Bogor\",\"Address\":\"Cilebut\"}', 'Update user Member succesfully by Muhammad Fajar', '2017-10-12 14:39:58', 'U', '2');
INSERT INTO `logs` VALUES ('65', '1', '{\"Menu Code\":\"7\",\"Menu Name\":\"Tets\",\"Menu Link\":\"stse\",\"Lang\":\"sets\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', null, null, 'Add menu Tets succesfully by Administrator', '2017-10-12 14:44:50', 'C', '1');
INSERT INTO `logs` VALUES ('66', '1', '{\"Menu Code\":\"7\",\"Menu Name\":\"Test\",\"Menu Link\":\"stse\",\"Lang\":\"sets\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', '{\"Menu Code\":7,\"Menu Name\":\"Tets\",\"Menu Link\":\"stse\",\"Lang\":\"sets\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', '{\"Menu Name\":\"Test\"}', 'Update menu Test succesfully by Administrator', '2017-10-12 14:44:58', 'U', '1');
INSERT INTO `logs` VALUES ('67', '1', null, '{\"Menu Code\":7,\"Menu Name\":\"Test\",\"Menu Link\":\"stse\",\"Lang\":\"sets\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', null, 'Delete menu Test succesfully by Administrator', '2017-10-12 14:45:03', 'D', '1');
INSERT INTO `logs` VALUES ('68', '1', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"Bogor\",\"Address\":\"Cileungsi\",\"Role \":\"General User\"}', '{\"Full Name\":\"Muhammad Fajar\",\"Email\":\"Fajar@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"0812345\",\"City\":\"Bogor\",\"Address\":\"Cileungsi\",\"Role \":\"Administrator\"}', '{\"Role \":\"General User\"}', 'Update user Muhammad Fajar succesfully by Administrator', '2017-10-12 15:30:35', 'U', '2');
INSERT INTO `logs` VALUES ('69', '1', null, '{\"Status Usermenu\":\"Active\"}', null, 'Delete user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 15:59:46', 'D', '3');
INSERT INTO `logs` VALUES ('70', '1', null, '{\"Menu\":\"Transaction\",\"Status Usermenu\":\"Active\"}', null, 'Delete user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 16:01:00', 'D', '3');
INSERT INTO `logs` VALUES ('71', '1', null, '{\"Menu\":\"Reports\",\"Status Usermenu\":\"Not Active\"}', null, 'Delete user menu Muhammad Fajar succesfully by Administrator', '2017-10-12 16:01:49', 'D', '3');
INSERT INTO `logs` VALUES ('72', '1', '{\"First Name\":\"Admin\",\"Last Name\":\"istrator\",\"Email\":\"octavian91011@gmail.com1\",\"Address\":\"Cilebut1\",\"City\":\"Bogor1\",\"Phone\":\"+62878987654321\"}', '{\"First Name\":\"Octavian\",\"Last Name\":\"Panggestu\",\"Email\":\"octavian91011@gmail.com\",\"Address\":\"Cilebut\",\"City\":\"Bogor\",\"Phone\":\"+62878123456789\"}', '{\"First Name\":\"Admin\",\"Last Name\":\"istrator\",\"Email\":\"octavian91011@gmail.com1\",\"Address\":\"Cilebut1\",\"City\":\"Bogor1\",\"Phone\":\"+62878987654321\"}', 'Update user profile Administrator succesfully by Administrator', '2017-10-12 16:06:14', 'U', '2');
INSERT INTO `logs` VALUES ('73', '1', '{\"First Name\":\"Admin\",\"Last Name\":\"istrator\",\"Email\":\"octavian91011@gmail.com\",\"Address\":\"Cilebut\",\"City\":\"Bogor\",\"Phone\":\"+62878987654321\"}', '{\"First Name\":\"Admin\",\"Last Name\":\"istrator\",\"Email\":\"octavian91011@gmail.com1\",\"Address\":\"Cilebut1\",\"City\":\"Bogor1\",\"Phone\":\"+62878987654321\"}', '{\"Email\":\"octavian91011@gmail.com\",\"Address\":\"Cilebut\",\"City\":\"Bogor\"}', 'Update user profile Administrator succesfully by Administrator', '2017-10-12 16:07:17', 'U', '2');
INSERT INTO `logs` VALUES ('74', '1', '{\"Username\":\"admin\",\"First Name\":\"Octavian\",\"Last Name\":\"Panggestu\",\"Full Name\":\"Octavian Panggestu\",\"Email\":\"octavian91011@gmail.com\",\"Address\":\"Cilebut\",\"City\":\"Bogor\",\"Phone\":\"+62878987654321\"}', '{\"Username\":\"administrator\",\"First Name\":\"Admin\",\"Last Name\":\"istrator\",\"Full Name\":\"Admin istrator\",\"Email\":\"octavian91011@gmail.com\",\"Address\":\"Cilebut\",\"City\":\"Bogor\",\"Phone\":\"+62878987654321\"}', '{\"Username\":\"admin\",\"First Name\":\"Octavian\",\"Last Name\":\"Panggestu\",\"Full Name\":\"Octavian Panggestu\"}', 'Update user profile Administrator succesfully by Administrator', '2017-10-12 17:17:18', 'U', '2');
INSERT INTO `logs` VALUES ('75', '1', '{\"Username\":\"admin\",\"First Name\":\"Octavian\",\"Last Name\":\"Panggestu\",\"Full Name\":\"Octavian Panggestu\",\"Email\":\"octavian91011@gmail.com\",\"Address\":\"Cilebut\",\"City\":\"Bogor\",\"Phone\":\"+62878987654321\"}', '{\"Username\":\"admin\",\"First Name\":\"Octavian\",\"Last Name\":\"Panggestu\",\"Full Name\":\"Octavian Panggestu\",\"Email\":\"octavian91011@gmail.com\",\"Address\":\"Cilebut\",\"City\":\"Bogor\",\"Phone\":\"+62878987654321\"}', '[]', 'Update user profile Octavian Panggestu succesfully by Octavian Panggestu', '2017-10-12 17:20:45', 'U', '2');
INSERT INTO `logs` VALUES ('76', '1', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"No\",\"Viewed\":\"Yes\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Not Active\"}', '{\"Menu\":\"Menus\",\"Created\":\"No\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Status Usermenu\":\"Active\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:25:54', 'U', '3');
INSERT INTO `logs` VALUES ('77', '1', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"No\",\"Viewed\":\"Yes\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Created\":\"Yes\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:27:42', 'U', '3');
INSERT INTO `logs` VALUES ('78', '1', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Updated\":\"Yes\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:27:55', 'U', '3');
INSERT INTO `logs` VALUES ('79', '1', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Deleted\":\"Yes\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:28:07', 'U', '3');
INSERT INTO `logs` VALUES ('80', '1', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"No\",\"Status Usermenu\":\"Active\"}', '{\"Print Unlimited\":\"Yes\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:28:15', 'U', '3');
INSERT INTO `logs` VALUES ('81', '1', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"No\",\"Viewed\":\"Yes\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Created\":\"No\",\"Updated\":\"No\",\"Deleted\":\"No\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:28:51', 'U', '3');
INSERT INTO `logs` VALUES ('82', '1', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"No\",\"Viewed\":\"Yes\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Created\":\"Yes\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:29:14', 'U', '3');
INSERT INTO `logs` VALUES ('83', '1', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"No\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Updated\":\"Yes\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:31:10', 'U', '3');
INSERT INTO `logs` VALUES ('84', '1', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"No\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Deleted\":\"Yes\"}', 'Update user menu Muhammad Fajar succesfully by Octavian Panggestu', '2017-10-12 18:31:34', 'U', '3');
INSERT INTO `logs` VALUES ('85', '1', '{\"Full Name\":\"Edo\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Octavian Panggestu\",\"Email\":\"octavian@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Bogor\",\"Address\":\"Cilebut\",\"Role \":\"General User\"}', '{\"Full Name\":\"Edo\",\"Email\":\"edo@gmail.com\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\"}', 'Update user Octavian Panggestu succesfully by Octavian Panggestu', '2017-10-24 13:52:34', 'U', '2');
INSERT INTO `logs` VALUES ('86', '1', '{\"Full Name\":\"Edo\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Edo\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '[]', 'Update user Edo succesfully by Octavian Panggestu', '2017-10-24 14:00:46', 'U', '2');
INSERT INTO `logs` VALUES ('87', '1', '{\"Menu Code\":\"6\",\"Menu Name\":\"Brand\",\"Menu Link\":\"brand\",\"Lang\":\"brand\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', '{\"Menu Code\":6,\"Menu Name\":\"History\",\"Menu Link\":\"history\",\"Lang\":\"history\",\"Parent Menu\":\"-\",\"Status\":\"Not Active\"}', '{\"Menu Name\":\"Brand\",\"Menu Link\":\"brand\",\"Lang\":\"brand\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', 'Update menu Brand succesfully by Octavian Panggestu', '2017-10-31 09:50:36', 'U', '1');
INSERT INTO `logs` VALUES ('88', '1', '{\"Menu\":\"Brand\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Brand\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Not Active\"}', '{\"Status Usermenu\":\"Active\"}', 'Update user menu Octavian Panggestu succesfully by Octavian Panggestu', '2017-10-31 09:51:12', 'U', '3');
INSERT INTO `logs` VALUES ('89', '1', '{\"Brand Name\":\"ASPIRA\"}', '{\"Brand Name\":\"Aspira\"}', '{\"Brand Name\":\"ASPIRA\"}', 'Update brand ASPIRA succesfully by Octavian Panggestu', '2017-10-31 10:21:41', 'U', '4');
INSERT INTO `logs` VALUES ('90', '1', '{\"Brand Name\":\"BRIDGESTONE\"}', '{\"Brand Name\":\"Bridgestone\"}', '{\"Brand Name\":\"BRIDGESTONE\"}', 'Update brand BRIDGESTONE succesfully by Octavian Panggestu', '2017-10-31 10:29:38', 'U', '4');
INSERT INTO `logs` VALUES ('91', '1', '{\"Brand Name\":\"MICHELLIN\"}', '{\"Brand Name\":\"Michellin\"}', '{\"Brand Name\":\"MICHELLIN\"}', 'Update brand MICHELLIN succesfully by Octavian Panggestu', '2017-10-31 10:30:05', 'U', '4');
INSERT INTO `logs` VALUES ('92', '1', '{\"Brand Name\":\"TEST\"}', null, null, 'Add brand TEST succesfully by Octavian Panggestu', '2017-10-31 10:46:16', 'C', '4');
INSERT INTO `logs` VALUES ('93', '1', '{\"Brand Name\":\"INK\"}', '{\"Brand Name\":\"TEST\"}', '{\"Brand Name\":\"INK\"}', 'Update brand INK succesfully by Octavian Panggestu', '2017-10-31 10:46:34', 'U', '4');
INSERT INTO `logs` VALUES ('94', '1', null, '{\"Brand Name\":null}', null, 'Delete brand INK succesfully by Octavian Panggestu', '2017-10-31 10:48:26', 'D', '4');
INSERT INTO `logs` VALUES ('95', '1', null, '{\"Brand Name\":\"INK\"}', null, 'Delete brand INK succesfully by Octavian Panggestu', '2017-10-31 10:50:30', 'D', '4');
INSERT INTO `logs` VALUES ('96', '1', '{\"Menu Code\":\"7\",\"Menu Name\":\"Area\",\"Menu Link\":\"area\",\"Lang\":\"area\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', null, null, 'Add menu Area succesfully by Octavian Panggestu', '2018-12-13 10:27:48', 'C', '1');
INSERT INTO `logs` VALUES ('97', '1', '{\"User\":\"Octavian Panggestu\",\"Menu\":\"Area\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"Yes\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu Octavian Panggestu succesfully by Octavian Panggestu', '2018-12-13 10:28:08', 'C', '3');
INSERT INTO `logs` VALUES ('98', '1', '{\"Area Name\":\"JABODETABEK\"}', '{\"Area Name\":\"Jakarta\"}', '{\"Area Name\":\"JABODETABEK\"}', 'Update area JABODETABEK succesfully by Octavian Panggestu', '2018-12-13 11:04:02', 'U', '4');
INSERT INTO `logs` VALUES ('99', '1', '{\"Area Name\":\"MEDAN\"}', null, null, 'Add area MEDAN succesfully by Octavian Panggestu', '2018-12-13 11:04:14', 'C', '4');
INSERT INTO `logs` VALUES ('100', '1', '{\"Area Name\":\"SEMARANG\"}', '{\"Area Name\":\"Semarang\"}', '{\"Area Name\":\"SEMARANG\"}', 'Update area SEMARANG succesfully by Octavian Panggestu', '2018-12-13 11:04:20', 'U', '4');
INSERT INTO `logs` VALUES ('101', '1', '{\"Area Name\":\"BANDUNG\"}', '{\"Area Name\":\"Bandung\"}', '{\"Area Name\":\"BANDUNG\"}', 'Update area BANDUNG succesfully by Octavian Panggestu', '2018-12-13 11:04:25', 'U', '4');
INSERT INTO `logs` VALUES ('102', '1', '{\"Area Name\":\"SURABAYA\"}', null, null, 'Add area SURABAYA succesfully by Octavian Panggestu', '2018-12-13 11:04:31', 'C', '4');
INSERT INTO `logs` VALUES ('103', '1', '{\"Area Name\":\"MAKASSAR\"}', null, null, 'Add area MAKASSAR succesfully by Octavian Panggestu', '2018-12-13 11:04:51', 'C', '4');
INSERT INTO `logs` VALUES ('104', '1', '{\"Area Name\":\"BANJARMASIN\"}', '{\"Area Name\":\"MAKASSAR\"}', '{\"Area Name\":\"BANJARMASIN\"}', 'Update area BANJARMASIN succesfully by Octavian Panggestu', '2018-12-13 11:05:05', 'U', '4');
INSERT INTO `logs` VALUES ('105', '1', '{\"Area Name\":\"BALI\"}', '{\"Area Name\":\"BANJARMASIN\"}', '{\"Area Name\":\"BALI\"}', 'Update area BALI succesfully by Octavian Panggestu', '2018-12-13 11:05:18', 'U', '4');
INSERT INTO `logs` VALUES ('106', '1', null, '{\"Area Name\":\"BALI\"}', null, 'Delete area BALI succesfully by Octavian Panggestu', '2018-12-13 11:05:25', 'D', '4');
INSERT INTO `logs` VALUES ('107', '1', '{\"Area Name\":\"JAKARTA\"}', '{\"Area Name\":\"JABODETABEK\"}', '{\"Area Name\":\"JAKARTA\"}', 'Update area JAKARTA succesfully by Octavian Panggestu', '2018-12-13 11:12:23', 'U', '5');
INSERT INTO `logs` VALUES ('108', '1', '{\"Area Name\":\"BALI\"}', null, null, 'Add area BALI succesfully by Octavian Panggestu', '2018-12-13 11:14:08', 'C', '5');
INSERT INTO `logs` VALUES ('109', '1', null, '{\"Area Name\":\"BALI\"}', null, 'Delete area BALI succesfully by Octavian Panggestu', '2018-12-13 11:14:12', 'D', '5');
INSERT INTO `logs` VALUES ('110', '1', '{\"Menu Code\":1}', '{\"Menu Code\":1}', '[]', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-24 00:03:36', 'U', '1');
INSERT INTO `logs` VALUES ('111', '1', '{\"Menu Code\":1}', '{\"Menu Code\":1}', '[]', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-25 01:13:44', 'U', '1');
INSERT INTO `logs` VALUES ('112', '1', '{\"Menu Code\":2}', '{\"Menu Code\":1}', '{\"Menu Code\":2}', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-25 01:14:40', 'U', '1');
INSERT INTO `logs` VALUES ('113', '1', '{\"Menu Code\":1}', '{\"Menu Code\":2}', '{\"Menu Code\":1}', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-25 01:15:03', 'U', '1');
INSERT INTO `logs` VALUES ('114', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Master\",\"Menu Link\":\"masters\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', null, null, 'Add menu Master succesfully by Octavian Panggestu', '2019-04-25 01:16:17', 'C', '1');
INSERT INTO `logs` VALUES ('115', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Mastera\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', null, null, 'Add menu Mastera succesfully by Octavian Panggestu', '2019-04-25 01:16:51', 'C', '1');
INSERT INTO `logs` VALUES ('116', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Mastera\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Code\":1,\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Name\":\"Mastera\"}', 'Update menu Mastera succesfully by Octavian Panggestu', '2019-04-25 01:19:58', 'U', '1');
INSERT INTO `logs` VALUES ('117', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Code\":1,\"Menu Name\":\"Mastera\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Name\":\"Master\"}', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-25 01:20:12', 'U', '1');
INSERT INTO `logs` VALUES ('118', '1', null, '{\"Menu Code\":1,\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', null, 'Delete menu Master succesfully by Octavian Panggestu', '2019-04-25 01:20:46', 'D', '1');
INSERT INTO `logs` VALUES ('119', '1', null, '{\"Menu Code\":1,\"Menu Name\":\"Mastera\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', null, 'Delete menu Mastera succesfully by Octavian Panggestu', '2019-04-25 01:21:21', 'D', '1');
INSERT INTO `logs` VALUES ('120', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Mastera\",\"Menu Link\":\"masters\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Code\":1,\"Menu Name\":\"Master\",\"Menu Link\":\"masters\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Name\":\"Mastera\"}', 'Update menu Mastera succesfully by Octavian Panggestu', '2019-04-25 01:21:37', 'U', '1');
INSERT INTO `logs` VALUES ('121', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Master\",\"Menu Link\":\"masters\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Code\":1,\"Menu Name\":\"Mastera\",\"Menu Link\":\"masters\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Name\":\"Master\"}', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-25 01:22:41', 'U', '1');
INSERT INTO `logs` VALUES ('122', '1', '{\"Full Name\":\"Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Edo\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Edo Gustian\"}', 'Update user Edo succesfully by Octavian Panggestu', '2019-04-27 07:31:13', 'U', '2');
INSERT INTO `logs` VALUES ('123', '1', '{\"User\":\"Edo Gustian\",\"Menu\":\"Master\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu Edo Gustian succesfully by Octavian Panggestu', '2019-04-27 07:31:37', 'C', '3');
INSERT INTO `logs` VALUES ('124', '1', '{\"Menu\":\"Master\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"No\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Master\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Fullaccess\":\"No\"}', 'Update user menu Edo Gustian succesfully by Octavian Panggestu', '2019-04-27 07:31:55', 'U', '3');
INSERT INTO `logs` VALUES ('125', '1', null, '{\"Menu\":\"Master\",\"Status Usermenu\":\"Not Active\"}', null, 'Delete user menu Edo Gustian succesfully by Octavian Panggestu', '2019-04-27 07:32:08', 'D', '3');
INSERT INTO `logs` VALUES ('126', '1', '{\"Full Name\":\"Muhhamad Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Muhhamad Edo Gustian\"}', 'Update user Edo Gustian succesfully by Octavian Panggestu', '2019-04-27 07:41:19', 'U', '2');
INSERT INTO `logs` VALUES ('127', '1', '{\"Full Name\":\"Muhammad Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Muhhamad Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Muhammad Edo Gustian\"}', 'Update user Muhhamad Edo Gustian succesfully by Octavian Panggestu', '2019-04-27 07:41:32', 'U', '2');
INSERT INTO `logs` VALUES ('128', '1', '{\"Full Name\":\"Muhammad Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Muhammad Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '[]', 'Update user Muhammad Edo Gustian succesfully by Octavian Panggestu', '2019-04-27 07:41:39', 'U', '2');
INSERT INTO `logs` VALUES ('129', '1', null, '{\"Status\":\"Active\"}', null, 'Delete user Muhammad Fajar succesfully by Octavian Panggestu', '2019-04-27 07:45:07', 'D', '2');
INSERT INTO `logs` VALUES ('130', '1', null, '{\"Status\":\"Active\"}', null, 'Delete user Muhammad Fajar succesfully by Octavian Panggestu', '2019-04-27 07:46:18', 'D', '2');
INSERT INTO `logs` VALUES ('131', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Master1\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Code\":1,\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Name\":\"Master1\"}', 'Update menu Master1 succesfully by Octavian Panggestu', '2019-04-27 07:47:05', 'U', '1');
INSERT INTO `logs` VALUES ('132', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Code\":1,\"Menu Name\":\"Master1\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Name\":\"Master\"}', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-27 07:47:12', 'U', '1');
INSERT INTO `logs` VALUES ('133', '1', null, '{\"Menu Code\":1,\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', null, 'Delete menu Master succesfully by Octavian Panggestu', '2019-04-27 07:47:43', 'D', '1');
INSERT INTO `logs` VALUES ('134', '1', null, '{\"Menu Code\":7,\"Menu Name\":\"Area\",\"Menu Link\":\"area\",\"Lang\":\"area\",\"Parent Menu\":\"Master\",\"Status\":\"Not Active\"}', null, 'Delete menu Area succesfully by Octavian Panggestu', '2019-04-27 07:52:07', 'D', '1');
INSERT INTO `logs` VALUES ('135', '1', '{\"Menu Code\":\"7\",\"Menu Name\":\"Area\",\"Menu Link\":\"area\",\"Lang\":\"area\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', '{\"Menu Code\":7,\"Menu Name\":\"Area\",\"Menu Link\":\"area\",\"Lang\":\"area\",\"Parent Menu\":\"Master\",\"Status\":\"Not Active\"}', '{\"Status\":\"Active\"}', 'Update menu Area succesfully by Octavian Panggestu', '2019-04-27 07:52:18', 'U', '1');
INSERT INTO `logs` VALUES ('136', '1', '{\"Brand Name\":\"NOKIA\"}', '{\"Brand Name\":\"ASPIRA\"}', '{\"Brand Name\":\"NOKIA\"}', 'Update brand NOKIA succesfully by Octavian Panggestu', '2019-04-27 07:55:32', 'U', '4');
INSERT INTO `logs` VALUES ('137', '1', null, '{\"Brand Name\":\"NOKIA\"}', null, 'Delete brand NOKIA succesfully by Octavian Panggestu', '2019-04-27 07:55:52', 'D', '4');
INSERT INTO `logs` VALUES ('138', '1', '{\"Area Name\":\"MALUKU\"}', '{\"Area Name\":\"SURABAYA\"}', '{\"Area Name\":\"MALUKU\"}', 'Update area MALUKU succesfully by Octavian Panggestu', '2019-04-27 07:58:51', 'U', '5');
INSERT INTO `logs` VALUES ('139', '1', '{\"Area Name\":\"MEDAN\"}', '{\"Area Name\":\"MALUKU\"}', '{\"Area Name\":\"MEDAN\"}', 'Update area MEDAN succesfully by Octavian Panggestu', '2019-04-27 07:59:51', 'U', '5');
INSERT INTO `logs` VALUES ('140', '1', null, '{\"Area Name\":\"MEDAN\"}', null, 'Delete area MEDAN succesfully by Octavian Panggestu', '2019-04-27 08:00:09', 'D', '5');
INSERT INTO `logs` VALUES ('141', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Code\":1,\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '[]', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-27 23:49:54', 'U', '1');
INSERT INTO `logs` VALUES ('142', '1', '{\"Full Name\":\"Muhammad Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Muhammad Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '[]', 'Update user Muhammad Edo Gustian succesfully by Octavian Panggestu', '2019-04-27 23:52:02', 'U', '2');
INSERT INTO `logs` VALUES ('143', '1', '{\"Full Name\":\"Muhammad Edo\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Muhammad Edo Gustian\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"General User\"}', '{\"Full Name\":\"Muhammad Edo\"}', 'Update user Muhammad Edo Gustian succesfully by Octavian Panggestu', '2019-04-27 23:54:09', 'U', '2');
INSERT INTO `logs` VALUES ('144', '1', '{\"Menu Code\":\"1\",\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '{\"Menu Code\":1,\"Menu Name\":\"Master\",\"Menu Link\":\"master\",\"Lang\":\"master\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', '[]', 'Update menu Master succesfully by Octavian Panggestu', '2019-04-27 23:54:40', 'U', '1');
INSERT INTO `logs` VALUES ('145', '1', '{\"Brand Name\":\"BRIDGESTONE\"}', '{\"Brand Name\":\"BRIDGESTONE\"}', '[]', 'Update brand BRIDGESTONE succesfully by Octavian Panggestu', '2019-04-27 23:55:43', 'U', '4');
INSERT INTO `logs` VALUES ('146', '1', '{\"Area Name\":\"BANDUNG\"}', '{\"Area Name\":\"BANDUNG\"}', '[]', 'Update area BANDUNG succesfully by Octavian Panggestu', '2019-04-27 23:56:01', 'U', '5');
INSERT INTO `logs` VALUES ('147', '1', '{\"Menu\":\"Master\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"No\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Master\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"No\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Not Active\"}', '{\"Status Usermenu\":\"Active\"}', 'Update user menu Muhammad Edo succesfully by Octavian Panggestu', '2019-04-27 23:56:32', 'U', '3');
INSERT INTO `logs` VALUES ('148', '1', '{\"Full Name\":\"DIPO Jatinegara\",\"Email\":\"dipo-jatinegara@gmail.com\",\"Company\":\"Kanaka\",\"Phone\":\"085123567123\",\"City\":\"Jakarta Timur\",\"Address\":\"Jalan Jatinegara 12\",\"Role \":\"DIPO\"}', '{\"Full Name\":\"Muhammad Edo\",\"Email\":\"edo@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"085123567\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Benda No 92\",\"Role \":\"DIPO\"}', '{\"Full Name\":\"DIPO Jatinegara\",\"Email\":\"dipo-jatinegara@gmail.com\",\"Company\":\"Kanaka\",\"Phone\":\"085123567123\",\"City\":\"Jakarta Timur\",\"Address\":\"Jalan Jatinegara 12\"}', 'Update user Muhammad Edo succesfully by Octavian Panggestu', '2019-04-28 00:24:12', 'U', '2');
INSERT INTO `logs` VALUES ('149', '1', '{\"Full Name\":\"PT Kanaka\",\"Email\":\"admin@kanaka.com\",\"Company\":\"PT KANAKA\",\"Phone\":\"+62878987654321\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Sudirman No 1\",\"Role \":\"Company\"}', '{\"Full Name\":\"Octavian Panggestu\",\"Email\":\"octavian91011@gmail.com\",\"Company\":\"Nadyne\",\"Phone\":\"+62878987654321\",\"City\":\"Bogor\",\"Address\":\"Cilebut\",\"Role \":\"Company\"}', '{\"Full Name\":\"PT Kanaka\",\"Email\":\"admin@kanaka.com\",\"Company\":\"PT KANAKA\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Sudirman No 1\"}', 'Update user Octavian Panggestu succesfully by Octavian Panggestu', '2019-04-28 00:24:52', 'U', '2');
INSERT INTO `logs` VALUES ('150', '1', '{\"Full Name\":\"Mitra Beras Jatinegara\",\"Email\":\"mitra_beras_jatinegara@kanaka.com\",\"Role\":\"Mitra\",\"Company\":\"PT Kanaka\",\"Phone\":\"0212378176\"}', null, null, 'Add user Mitra Beras Jatinegara succesfully by PT Kanaka', '2019-04-28 00:25:44', 'C', '2');
INSERT INTO `logs` VALUES ('151', '1', '{\"Full Name\":\"PT Kanaka\",\"Email\":\"admin@kanaka.com\",\"Company\":\"PT Kanaka\",\"Phone\":\"+62878987654321\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Sudirman No 1\",\"Role \":\"Company\"}', '{\"Full Name\":\"PT Kanaka\",\"Email\":\"admin@kanaka.com\",\"Company\":\"PT KANAKA\",\"Phone\":\"+62878987654321\",\"City\":\"Jakarta Selatan\",\"Address\":\"Jalan Sudirman No 1\",\"Role \":\"Company\"}', '{\"Company\":\"PT Kanaka\"}', 'Update user PT Kanaka succesfully by PT Kanaka', '2019-04-28 00:25:57', 'U', '2');
INSERT INTO `logs` VALUES ('152', '1', '{\"Full Name\":\"DIPO Jatinegara\",\"Email\":\"dipo-jatinegara@gmail.com\",\"Company\":\"PT Kanaka\",\"Phone\":\"085123567123\",\"City\":\"Jakarta Timur\",\"Address\":\"Jalan Jatinegara 12\",\"Role \":\"DIPO\"}', '{\"Full Name\":\"DIPO Jatinegara\",\"Email\":\"dipo-jatinegara@gmail.com\",\"Company\":\"Kanaka\",\"Phone\":\"085123567123\",\"City\":\"Jakarta Timur\",\"Address\":\"Jalan Jatinegara 12\",\"Role \":\"DIPO\"}', '{\"Company\":\"PT Kanaka\"}', 'Update user DIPO Jatinegara succesfully by PT Kanaka', '2019-04-28 00:26:05', 'U', '2');
INSERT INTO `logs` VALUES ('153', '1', '{\"User\":\"Mitra Beras Jatinegara\",\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu Mitra Beras Jatinegara succesfully by PT Kanaka', '2019-04-28 00:39:35', 'C', '3');
INSERT INTO `logs` VALUES ('154', '1', '{\"User\":\"Mitra Beras Jatinegara\",\"Menu\":\"Transaction\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu Mitra Beras Jatinegara succesfully by PT Kanaka', '2019-04-28 00:39:43', 'C', '3');
INSERT INTO `logs` VALUES ('155', '1', '{\"Menu\":\"Reports\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Users\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Reports\"}', 'Update user menu DIPO Jatinegara succesfully by PT Kanaka', '2019-04-28 00:40:47', 'U', '3');
INSERT INTO `logs` VALUES ('156', '1', '{\"Menu\":\"Area\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Menus\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Area\"}', 'Update user menu DIPO Jatinegara succesfully by PT Kanaka', '2019-04-28 00:41:10', 'U', '3');
INSERT INTO `logs` VALUES ('157', '1', '{\"Menu Code\":\"8\",\"Menu Name\":\"Product\",\"Menu Link\":\"product\",\"Lang\":\"product\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', null, null, 'Add menu Product succesfully by PT Kanaka', '2019-04-28 20:19:00', 'C', '1');
INSERT INTO `logs` VALUES ('158', '1', null, '{\"Menu Code\":6,\"Menu Name\":\"Brand\",\"Menu Link\":\"brand\",\"Lang\":\"brand\",\"Parent Menu\":\"Master\",\"Status\":\"Not Active\"}', null, 'Delete menu Brand succesfully by PT Kanaka', '2019-04-28 20:19:05', 'D', '1');
INSERT INTO `logs` VALUES ('159', '1', null, '{\"Menu Code\":7,\"Menu Name\":\"Area\",\"Menu Link\":\"area\",\"Lang\":\"area\",\"Parent Menu\":\"Master\",\"Status\":\"Not Active\"}', null, 'Delete menu Area succesfully by PT Kanaka', '2019-04-28 20:19:11', 'D', '1');
INSERT INTO `logs` VALUES ('160', '1', '{\"Menu Code\":\"9\",\"Menu Name\":\"DIPO\",\"Menu Link\":\"dipo\",\"Lang\":\"dipo\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', null, null, 'Add menu DIPO succesfully by PT Kanaka', '2019-04-28 20:19:30', 'C', '1');
INSERT INTO `logs` VALUES ('161', '1', '{\"Menu Code\":\"10\",\"Menu Name\":\"Partner\",\"Menu Link\":\"partner\",\"Lang\":\"partner\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', null, null, 'Add menu Partner succesfully by PT Kanaka', '2019-04-28 20:19:55', 'C', '1');
INSERT INTO `logs` VALUES ('162', '1', '{\"Menu Code\":\"11\",\"Menu Name\":\"Transfer\",\"Menu Link\":\"transfer\",\"Lang\":\"transfer\",\"Parent Menu\":\"Master\",\"Status\":\"Active\"}', null, null, 'Add menu Transfer succesfully by PT Kanaka', '2019-04-28 20:20:13', 'C', '1');
INSERT INTO `logs` VALUES ('163', '1', null, '{\"Menu Code\":2,\"Menu Name\":\"Transaction\",\"Menu Link\":\"transaction\",\"Lang\":\"transaction\",\"Parent Menu\":\"-\",\"Status\":\"Not Active\"}', null, 'Delete menu Transaction succesfully by PT Kanaka', '2019-04-28 20:20:27', 'D', '1');
INSERT INTO `logs` VALUES ('164', '1', '{\"Menu Code\":\"12\",\"Menu Name\":\"Customer\",\"Menu Link\":\"customer\",\"Lang\":\"customer\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', null, null, 'Add menu Customer succesfully by PT Kanaka', '2019-04-28 20:21:08', 'C', '1');
INSERT INTO `logs` VALUES ('165', '1', '{\"Menu Code\":\"13\",\"Menu Name\":\"Company\",\"Menu Link\":\"company\",\"Lang\":\"company\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', null, null, 'Add menu Company succesfully by PT Kanaka', '2019-04-28 20:21:29', 'C', '1');
INSERT INTO `logs` VALUES ('166', '1', '{\"Menu Code\":\"14\",\"Menu Name\":\"DIPO\",\"Menu Link\":\"dipo_report\",\"Lang\":\"dipo_report\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', null, null, 'Add menu DIPO succesfully by PT Kanaka', '2019-04-28 20:22:00', 'C', '1');
INSERT INTO `logs` VALUES ('167', '1', '{\"Menu Code\":\"15\",\"Menu Name\":\"Partner\",\"Menu Link\":\"partner_report\",\"Lang\":\"partner_report\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', null, null, 'Add menu Partner succesfully by PT Kanaka', '2019-04-28 20:22:20', 'C', '1');
INSERT INTO `logs` VALUES ('168', '1', '{\"Menu Code\":\"16\",\"Menu Name\":\"Admin\",\"Menu Link\":\"admin\",\"Lang\":\"admin\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', null, null, 'Add menu Admin succesfully by PT Kanaka', '2019-04-28 20:22:36', 'C', '1');
INSERT INTO `logs` VALUES ('169', '1', '{\"Menu Code\":\"17\",\"Menu Name\":\"Blog\",\"Menu Link\":\"blog\",\"Lang\":\"blog\",\"Parent Menu\":\"-\",\"Status\":\"Active\"}', null, null, 'Add menu Blog succesfully by PT Kanaka', '2019-04-28 20:22:47', 'C', '1');
INSERT INTO `logs` VALUES ('170', '1', '{\"Menu Code\":\"14\",\"Menu Name\":\"DIPO Report\",\"Menu Link\":\"dipo_report\",\"Lang\":\"dipo_report\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', '{\"Menu Code\":14,\"Menu Name\":\"DIPO\",\"Menu Link\":\"dipo_report\",\"Lang\":\"dipo_report\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', '{\"Menu Name\":\"DIPO Report\"}', 'Update menu DIPO Report succesfully by PT Kanaka', '2019-04-28 20:23:40', 'U', '1');
INSERT INTO `logs` VALUES ('171', '1', '{\"Menu Code\":\"15\",\"Menu Name\":\"Partner Report\",\"Menu Link\":\"partner_report\",\"Lang\":\"partner_report\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', '{\"Menu Code\":15,\"Menu Name\":\"Partner\",\"Menu Link\":\"partner_report\",\"Lang\":\"partner_report\",\"Parent Menu\":\"Reports\",\"Status\":\"Active\"}', '{\"Menu Name\":\"Partner Report\"}', 'Update menu Partner Report succesfully by PT Kanaka', '2019-04-28 20:23:51', 'U', '1');
INSERT INTO `logs` VALUES ('172', '1', '{\"Menu\":\"Customer\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Area\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"Yes\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Customer\",\"Print Limited\":\"No\"}', 'Update user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:24:19', 'U', '3');
INSERT INTO `logs` VALUES ('173', '1', '{\"Menu\":\"Company\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Transaction\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Company\"}', 'Update user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:24:31', 'U', '3');
INSERT INTO `logs` VALUES ('174', '1', '{\"User\":\"PT Kanaka\",\"Menu\":\"DIPO Report\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:24:53', 'C', '3');
INSERT INTO `logs` VALUES ('175', '1', '{\"Menu\":\"Partner Report\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Brand\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', '{\"Menu\":\"Partner Report\"}', 'Update user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:25:19', 'U', '3');
INSERT INTO `logs` VALUES ('176', '1', '{\"User\":\"PT Kanaka\",\"Menu\":\"Product\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:26:07', 'C', '3');
INSERT INTO `logs` VALUES ('177', '1', '{\"User\":\"PT Kanaka\",\"Menu\":\"DIPO\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:26:30', 'C', '3');
INSERT INTO `logs` VALUES ('178', '1', '{\"User\":\"PT Kanaka\",\"Menu\":\"Partner\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:26:47', 'C', '3');
INSERT INTO `logs` VALUES ('179', '1', '{\"User\":\"PT Kanaka\",\"Menu\":\"Transfer\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:26:57', 'C', '3');
INSERT INTO `logs` VALUES ('180', '1', '{\"User\":\"PT Kanaka\",\"Menu\":\"Admin\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:27:12', 'C', '3');
INSERT INTO `logs` VALUES ('181', '1', '{\"User\":\"PT Kanaka\",\"Menu\":\"Blog\",\"Availabled\":\"Yes\",\"Created\":\"Yes\",\"Viewed\":\"Yes\",\"Updated\":\"Yes\",\"Deleted\":\"Yes\",\"Approved\":\"Yes\",\"Verified\":\"Yes\",\"Fullaccess\":\"Yes\",\"Print Limited\":\"No\",\"Print Unlimited\":\"Yes\",\"Status Usermenu\":\"Active\"}', null, null, 'Add user menu PT Kanaka succesfully by PT Kanaka', '2019-04-28 20:27:21', 'C', '3');
INSERT INTO `logs` VALUES ('182', '1', '{\"Name\":\"\",\"Address\":\"Jalan Pajajaran No 10\",\"Phone\":\"02518790654\",\"Email\":\"dipobogor@kanaka.com\",\"City\":\"Bogor\",\"Subdistrict\":\"Bogor Tengah\",\"Latitude\":\"8098898999\",\"Longitude\":\"-889898989\"}', null, null, 'Add dipo  succesfully by PT Kanaka', '2019-05-01 22:10:29', 'C', '8');
INSERT INTO `logs` VALUES ('183', '1', '{\"Name\":\"Bandung Store\",\"Address\":\"Jalan Asia Afrika No9\",\"Phone\":\"02318654257\",\"Email\":\"dipobandung@kanaka.com\",\"City\":\"Bandung\",\"Subdistrict\":\"Tamansari\",\"Latitude\":\"87817283791\",\"Longitude\":\"-8738827318\"}', null, null, 'Add dipo Bandung Store succesfully by PT Kanaka', '2019-05-01 22:14:50', 'C', '8');
INSERT INTO `logs` VALUES ('184', '1', '{\"Name\":\"Jakarta Store\",\"Address\":\"Jalan Kemang 20\",\"Phone\":\"0218765234\",\"Email\":\"dipojakarta@kanaka.com\",\"City\":\"Jakarta Selatan\",\"Subdistrict\":\"Pasar Minggu\",\"Latitude\":\"87971923719\",\"Longitude\":\"-8978196237\"}', null, null, 'Add dipo Jakarta Store succesfully by PT Kanaka', '2019-05-01 22:25:23', 'C', '8');
INSERT INTO `logs` VALUES ('185', '1', '{\"Name\":\"Bandung Store 1\",\"Address\":\"Jalan Asia Afrika No 19\",\"Phone\":\"02318654259\",\"Email\":\"dipobandungstore@kanaka.com\",\"City\":\"Bandung Barat\",\"Subdistrict\":\"Ciwidey\",\"Latitude\":\"87817283799\",\"Longitude\":\"-8738827319\"}', '{\"Name\":\"Bandung Store\",\"Address\":\"Jalan Asia Afrika No9\",\"Phone\":\"02318654257\",\"Email\":\"dipobandung@kanaka.com\",\"City\":\"Bandung\",\"Subdistrict\":\"Tamansari\",\"Latitude\":\"87817283791\",\"Longitude\":\"-8738827318\"}', '{\"Name\":\"Bandung Store 1\",\"Address\":\"Jalan Asia Afrika No 19\",\"Phone\":\"02318654259\",\"Email\":\"dipobandungstore@kanaka.com\",\"City\":\"Bandung Barat\",\"Subdistrict\":\"Ciwidey\",\"Latitude\":\"87817283799\",\"Longitude\":\"-8738827319\"}', 'Update dipo Bandung Store 1 succesfully by PT Kanaka', '2019-05-01 23:04:32', 'U', '8');
INSERT INTO `logs` VALUES ('186', '1', null, '{\"Name\":\"Bandung Store 1\",\"Address\":\"Jalan Asia Afrika No 19\",\"Phone\":\"02318654259\",\"Email\":\"dipobandungstore@kanaka.com\",\"City\":\"Bandung Barat\",\"Subdistrict\":\"Ciwidey\",\"Latitude\":\"87817283799\",\"Longitude\":\"-8738827319\"}', null, 'Delete dipo Bandung Store 1 succesfully by PT Kanaka', '2019-05-01 23:05:28', 'D', '8');
